apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go_service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go_service
  template:
    metadata:
      labels:
        app: go_service
    spec:
      containers:
      - name: goservice
        image: fastleone/goapp:with_env
        env:
        - name: METRICS
          value: "true"
        ports:
        - containerPort: 80
